name: 'Terraform CI/CD Pipeline'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TF_VERSION: '1.7.4'
  AZURE_REGION: 'eastus'

jobs:
  terraform:
    name: 'Terraform Format, Validate, Plan, and Apply'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [dev, prod]

    defaults:
      run:
        shell: bash
        working-directory: ./envs/${{ matrix.environment }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Optional: Terraform Apply (Controlled by Manual Trigger or Flag)
      - name: Terraform Apply (only on push to main)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
